export type Idiom = {
  text: string;
  meaning: string;
};

export const WORD_LIST: Idiom[] = [
  { text: "유비무환", meaning: "미리 준비해 두면 걱정할 일이 없다" },
  { text: "새옹지마", meaning: "인생의 화와 복은 예측할 수 없다" },
  { text: "온고지신", meaning: "옛것을 익혀서 새것을 안다" },
  { text: "자업자득", meaning: "자기가 저지른 일의 결과를 자기가 받는다" },
  { text: "결자해지", meaning: "일을 벌인 사람이 그 일을 해결해야 한다" },
  { text: "십중팔구", meaning: "열 가운데 여덟이나 아홉, 거의 대부분" },
  { text: "일석이조", meaning: "돌 하나로 새 두 마리를 잡는다" },
  { text: "등하불명", meaning: "등잔 밑이 어둡다, 가까운 것을 오히려 모른다" },
  { text: "마이동풍", meaning: "남의 말을 귀담아듣지 않고 흘려버린다" },
  { text: "오리무중", meaning: "안개 속처럼 일의 갈피를 잡을 수 없다" },
  { text: "임기응변", meaning: "그때그때 상황에 맞게 알맞게 대처한다" },
  { text: "자화자찬", meaning: "자기가 한 일을 스스로 칭찬한다" },
  { text: "청출어람", meaning: "제자가 스승보다 뛰어나다" },
  { text: "표리부동", meaning: "겉과 속이 다르다" },
  { text: "호시탐탐", meaning: "기회를 노리며 가만히 형세를 살핀다" },
  { text: "감언이설", meaning: "귀에 듣기 좋은 말로 남을 꾀어낸다" },
  { text: "각주구검", meaning: "융통성 없이 낡은 방법만 고집한다" },
  { text: "개과천선", meaning: "잘못을 뉘우치고 착하게 바뀐다" },
  { text: "격세지감", meaning: "많이 변해서 딴 세상처럼 느껴진다" },
  { text: "고진감래", meaning: "고생 끝에 즐거움이 온다" },
  { text: "과유불급", meaning: "지나친 것은 모자란 것만 못하다" },
  { text: "근묵자흑", meaning: "나쁜 사람과 어울리면 물들기 쉽다" },
  { text: "다다익선", meaning: "많으면 많을수록 더 좋다" },
  { text: "대기만성", meaning: "큰 그릇은 늦게 만들어진다" },
  { text: "동상이몽", meaning: "같이 있으면서 서로 딴생각을 한다" },
  { text: "사면초가", meaning: "사방이 적으로 둘러싸여 도움받을 데가 없다" },
  { text: "설상가상", meaning: "눈 위에 서리, 어려운 일이 겹쳐 일어난다" },
  { text: "심사숙고", meaning: "깊이 잘 생각한다" },
  { text: "어부지리", meaning: "둘이 다투는 사이 엉뚱한 사람이 이익을 본다" },
  { text: "유유상종", meaning: "비슷한 사람끼리 서로 어울린다" },
  { text: "구사일생", meaning: "여러 번 죽을 고비를 넘기고 겨우 살아난다" },
  { text: "권토중래", meaning: "실패한 뒤 힘을 길러 다시 도전한다" },
  { text: "금상첨화", meaning: "좋은 것 위에 더 좋은 것이 더해진다" },
  { text: "기사회생", meaning: "거의 죽을 뻔하다가 다시 살아난다" },
  { text: "난공불락", meaning: "공격하기 어려워 좀처럼 함락되지 않는다" },
  { text: "노심초사", meaning: "몹시 마음을 쓰며 애를 태운다" },
  { text: "다사다난", meaning: "여러 가지 일도 많고 어려움도 많다" },
  { text: "대동소이", meaning: "큰 차이 없이 거의 비슷하다" },
  { text: "동고동락", meaning: "괴로움과 즐거움을 함께 나눈다" },
  { text: "두문불출", meaning: "집에만 있고 바깥출입을 하지 않는다" },
  { text: "막상막하", meaning: "실력이 비슷해서 우열을 가리기 어렵다" },
  { text: "명약관화", meaning: "불을 보듯 분명하다" },
  { text: "무용지물", meaning: "쓸모없는 물건이나 사람" },
  { text: "박학다식", meaning: "널리 배워 아는 것이 많다" },
  { text: "반신반의", meaning: "반쯤은 믿고 반쯤은 의심한다" },
  { text: "배은망덕", meaning: "은혜를 잊고 도리어 배신한다" },
  { text: "백년해로", meaning: "부부가 평생 함께 늙어간다" },
  { text: "백전백승", meaning: "싸울 때마다 모두 이긴다" },
  { text: "부지기수", meaning: "헤아릴 수 없을 만큼 많다" },
  { text: "분골쇄신", meaning: "뼈가 부서지도록 온 힘을 다한다" },
  { text: "비일비재", meaning: "같은 일이 한둘이 아니고 아주 흔하다" },
  { text: "사필귀정", meaning: "모든 일은 결국 옳은 데로 돌아간다" },
  { text: "산전수전", meaning: "온갖 고생과 어려움을 다 겪었다" },
  { text: "삼고초려", meaning: "인재를 얻으려고 정성껏 여러 번 찾아간다" },
  { text: "상부상조", meaning: "서로서로 돕는다" },
  { text: "새발의피", meaning: "아주 하찮고 적은 분량" },
  { text: "선견지명", meaning: "일이 일어나기 전에 미리 내다보는 지혜" },
  { text: "속수무책", meaning: "손을 묶은 듯 어찌할 방법이 없다" },
  { text: "수수방관", meaning: "팔짱 끼고 보기만 하며 나서지 않는다" },
  { text: "시시비비", meaning: "옳고 그름을 따진다" },
  { text: "식자우환", meaning: "아는 것이 오히려 걱정거리가 된다" },
  { text: "신출귀몰", meaning: "귀신처럼 자유자재로 나타났다 사라진다" },
  { text: "실사구시", meaning: "사실에 근거해 진리를 찾는다" },
  { text: "십시일반", meaning: "여럿이 조금씩 보태면 한 사람을 돕는다" },
  { text: "아전인수", meaning: "제 논에 물 대기, 자기에게 유리하게만 한다" },
  { text: "안하무인", meaning: "눈 아래 사람이 없다, 몹시 교만하다" },
  { text: "약육강식", meaning: "약한 자가 강한 자에게 먹힌다" },
  { text: "양자택일", meaning: "둘 중 하나를 골라야 한다" },
  { text: "어불성설", meaning: "말이 조금도 이치에 맞지 않는다" },
  { text: "언중유골", meaning: "예사로운 말 속에 단단한 뜻이 들어 있다" },
  { text: "역지사지", meaning: "처지를 바꾸어 상대편 입장에서 생각한다" },
  { text: "연목구어", meaning: "나무에서 물고기를 찾듯 불가능한 일을 한다" },
  { text: "오매불망", meaning: "자나 깨나 잊지 못한다" },
  { text: "오합지졸", meaning: "규율 없이 어중이떠중이 모인 무리" },
  { text: "우유부단", meaning: "망설이기만 하고 결단을 내리지 못한다" },
  { text: "우이독경", meaning: "쇠귀에 경 읽기, 말해도 알아듣지 못한다" },
  { text: "우후죽순", meaning: "비 온 뒤 죽순처럼 여기저기 생겨난다" },
  { text: "위풍당당", meaning: "위엄이 있고 기세가 씩씩하다" },
  { text: "유명무실", meaning: "이름만 있고 실속이 없다" },
  { text: "이구동성", meaning: "여러 사람이 입을 모아 같은 말을 한다" },
  { text: "이심전심", meaning: "말하지 않아도 마음에서 마음으로 통한다" },
  { text: "인과응보", meaning: "행한 대로 그에 맞는 결과를 받는다" },
  { text: "인산인해", meaning: "사람이 산과 바다를 이룰 만큼 많이 모였다" },
  { text: "일거양득", meaning: "한 가지 일로 두 가지 이익을 얻는다" },
  { text: "일망타진", meaning: "한꺼번에 모조리 잡는다" },
  { text: "일사천리", meaning: "일이 거침없이 빠르게 진행된다" },
  { text: "일취월장", meaning: "나날이 다달이 자라거나 발전한다" },
  { text: "일편단심", meaning: "변하지 않는 한결같은 마음" },
  { text: "일확천금", meaning: "힘 안 들이고 단번에 큰 재물을 얻는다" },
  { text: "자강불식", meaning: "스스로 힘써 쉬지 않고 노력한다" },
  { text: "자수성가", meaning: "물려받은 것 없이 스스로 집안을 일으킨다" },
  { text: "자초지종", meaning: "처음부터 끝까지의 사정" },
  { text: "적반하장", meaning: "잘못한 사람이 도리어 성을 낸다" },
  { text: "전화위복", meaning: "재앙이 바뀌어 오히려 복이 된다" },
  { text: "점입가경", meaning: "갈수록 더욱 재미있거나 꼴이 우스워진다" },
  { text: "조삼모사", meaning: "눈앞의 차이만 알고 결과가 같음은 모른다" },
  { text: "주객전도", meaning: "주인과 손님이 뒤바뀌듯 순서가 거꾸로다" },
  { text: "죽마고우", meaning: "어릴 때부터 같이 놀며 자란 벗" },
  { text: "중구난방", meaning: "여럿이 마구 떠들어 수습이 안 된다" },
  { text: "지피지기", meaning: "적을 알고 나를 안다" },
  { text: "진퇴양난", meaning: "나아갈 수도 물러설 수도 없는 처지" },
  { text: "천고마비", meaning: "하늘이 높고 말이 살찌는 좋은 가을철" },
  { text: "천재일우", meaning: "천 년에 한 번 올까 말까 한 좋은 기회" },
  { text: "초지일관", meaning: "처음에 세운 뜻을 끝까지 밀고 나간다" },
  { text: "칠전팔기", meaning: "일곱 번 넘어져도 여덟 번째 다시 일어난다" },
  { text: "타산지석", meaning: "남의 허물을 보고 자기를 바로잡는다" },
  { text: "탁상공론", meaning: "현실성 없는 헛된 이론이나 논의" },
  { text: "파죽지세", meaning: "대나무 쪼개듯 거침없이 밀고 나가는 기세" },
  { text: "팔방미인", meaning: "여러 방면에 두루 능한 사람" },
  { text: "풍전등화", meaning: "바람 앞의 등불처럼 몹시 위태롭다" },
  { text: "함흥차사", meaning: "심부름 간 사람이 소식조차 없다" },
  { text: "형설지공", meaning: "고생하며 부지런히 공부해 얻은 보람" },
  { text: "혼비백산", meaning: "몹시 놀라 넋을 잃는다" },
  { text: "화룡점정", meaning: "가장 중요한 부분을 마무리해 완성한다" },
  { text: "환골탈태", meaning: "완전히 새롭게 거듭난다" },
  { text: "횡설수설", meaning: "조리 없이 이러쿵저러쿵 함부로 지껄인다" },
  { text: "후회막급", meaning: "아무리 뉘우쳐도 돌이킬 수 없다" },
  { text: "흥진비래", meaning: "즐거운 일이 다하면 슬픈 일이 온다" },
];

export function pickRandomWord(exclude: Set<string>): Idiom {
  const available = WORD_LIST.filter((w) => !exclude.has(w.text));
  const pool = available.length > 0 ? available : WORD_LIST;
  return pool[Math.floor(Math.random() * pool.length)];
}
